I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 29, in script
    e "You've created a new Ren'Py game."
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 29, in script
    e "You've created a new Ren'Py game."
  File "renpy/ast.py", line 680, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
HomeSus 1.0
Fri May 21 10:49:25 2021
